language: ruby
sudo: false

rvm:
  - 2.2.5
  - 2.3.1
  - rbx
  - jruby

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.rails-4.2.x
  - gemfiles/Gemfile.rails-master

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
    - rvm: jruby
  fast_finish: true
